jobs:
  - source_id: cscec8_design
    company: 中建八局设计管理总院
    title: 设计管理总院2027届校园招聘
    location: [上海浦东新区]
    apply_url: https://job.cscec8b.com.cn/8bsjzy
    detail_url: https://job.cscec8b.com.cn/8bsjzy
    publish_date: 2026-06-18
    description: 2027届大学本科及以上学历，建筑学专业；CET-4及以上，党员和相关经历为优先条件。
